### ISSUE TITLE
修改网站对应的云盘目录

### ISSUE THREAD

**Issue by tudows** [tangshuang/WP2PCS#1]
如果是网址是带端口号的话，就无法在百度云盘里成功建立文件夹（因为百度云盘不接受“:”作为文件名），然后导致备份和资源两个功能都不能使用。我稍微修改了一下config-default.php就解决了这个问题，我希望作者可以考虑一下这个方案。

下面附上代码，修改的是这条语句“define('WP2PCS_SITE_URL’”，大致思路就是把“:”修改为“_”

这个是修改过的代码
define('WP2PCS_SITE_URL',str_replace(":","_",substr(home_url(),strpos(home_url(),'://')+3)));

**Comment by tangshuang** [comment]
@tudows 直接改 WP2PCS_BAIDUPCS_REMOTE_ROOT 就可以了

**Comment by tudows** [comment]
好的，了解

**Comment by hhyyqq5800** [comment]
现在这个插件还能用吗？

**Comment by tangshuang** [comment]
> 现在这个插件还能用吗？

应该是用不了了，百度云关闭了api key申请入口

**Comment by hhyyqq5800** [comment]
谢谢回复！那还有没有其他类似的wordpress插件能在网站中直接播放百度网盘中的音视频资源呢？



hhyyqq5800
 
发件人： 唐霜
发送时间： 2024-03-04 14:19
收件人： tangshuang/wp2pcs
抄送： hhyyqq5800; Comment
主题： Re: [tangshuang/wp2pcs] 修改网站对应的云盘目录 (#1)
现在这个插件还能用吗？
应该是用不了了，百度云关闭了api key申请入口

**Comment by tangshuang** [comment]
@hhyyqq5800 没有
